package com.js.phonicdiary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.js.phonicdiary.bean.DiaryInfo;
import com.js.phonicdiary.bean.PhotoInfo;
import com.js.phonicdiary.bean.VoiceInfo;

import com.js.phonicdiary.db.DiaryInfoDao;
import com.js.phonicdiary.db.PhotoInfoDao;
import com.js.phonicdiary.db.VoiceInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryInfoDaoConfig;
    private final DaoConfig photoInfoDaoConfig;
    private final DaoConfig voiceInfoDaoConfig;

    private final DiaryInfoDao diaryInfoDao;
    private final PhotoInfoDao photoInfoDao;
    private final VoiceInfoDao voiceInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryInfoDaoConfig = daoConfigMap.get(DiaryInfoDao.class).clone();
        diaryInfoDaoConfig.initIdentityScope(type);

        photoInfoDaoConfig = daoConfigMap.get(PhotoInfoDao.class).clone();
        photoInfoDaoConfig.initIdentityScope(type);

        voiceInfoDaoConfig = daoConfigMap.get(VoiceInfoDao.class).clone();
        voiceInfoDaoConfig.initIdentityScope(type);

        diaryInfoDao = new DiaryInfoDao(diaryInfoDaoConfig, this);
        photoInfoDao = new PhotoInfoDao(photoInfoDaoConfig, this);
        voiceInfoDao = new VoiceInfoDao(voiceInfoDaoConfig, this);

        registerDao(DiaryInfo.class, diaryInfoDao);
        registerDao(PhotoInfo.class, photoInfoDao);
        registerDao(VoiceInfo.class, voiceInfoDao);
    }
    
    public void clear() {
        diaryInfoDaoConfig.clearIdentityScope();
        photoInfoDaoConfig.clearIdentityScope();
        voiceInfoDaoConfig.clearIdentityScope();
    }

    public DiaryInfoDao getDiaryInfoDao() {
        return diaryInfoDao;
    }

    public PhotoInfoDao getPhotoInfoDao() {
        return photoInfoDao;
    }

    public VoiceInfoDao getVoiceInfoDao() {
        return voiceInfoDao;
    }

}
