package com.js.phonicdiary.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.js.phonicdiary.bean.DiaryInfo;

import com.js.phonicdiary.greenDao.db.DiaryInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig diaryInfoDaoConfig;

    private final DiaryInfoDao diaryInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        diaryInfoDaoConfig = daoConfigMap.get(DiaryInfoDao.class).clone();
        diaryInfoDaoConfig.initIdentityScope(type);

        diaryInfoDao = new DiaryInfoDao(diaryInfoDaoConfig, this);

        registerDao(DiaryInfo.class, diaryInfoDao);
    }
    
    public void clear() {
        diaryInfoDaoConfig.clearIdentityScope();
    }

    public DiaryInfoDao getDiaryInfoDao() {
        return diaryInfoDao;
    }

}
